### ISSUE TITLE
scope! appears in the readme but not in the code

### ISSUE THREAD

**Issue by mullr** [pangloss/clang#11]
It looks useful, I'd like to try it!

**Comment by pangloss** [comment]
I decided to remove `scope!` in 7a9ce9d0229dcb33451b0d663368c6394943dc1c when I extended the built-in JS data types with good support for clojure's standard protocols. I think this is better since the scope! macro didn't provide a lot of value and it's something extra to remember the semantics of when coming back to a project.

Setting a value: was `(scope! bool true)` now `(assoc! $scope :bool true)`

Reading a value: was `(scope! bool)` now `(:bool $scope)`

Of course, if you still want the scope! macro, you can get it from the above commit...

**Comment by mullr** [comment]
Oh, ok.  I guess then my only gripe is the inconsistency of the docs :)

**Comment by pangloss** [comment]
Yeah, just updating them now...

**Comment by mullr** [comment]
Excellent, thank you!
